DT = {
    'probe_id': '№ пробы',
    'order_id': '№ заказа',
    'executor_id': 'Лаборант',
    'date_ready': 'Дата исп.',
    'skv': '№ скв.',
    'probe_depth': 'Глуб. отбора',
    'soil_type': 'Тип грунта',
    'water_content': 'Прир. влажн.',
    'liquid_limit': 'Предел текуч.',
    'plastic_limit': 'Предел раск.',
    'plasticity_index': 'Число пласт.',
    'liquidity_index': 'Показат. консист.',
    'sito10': '>10',
    'sito5': '10-5',
    'sito2': '5-2',
    'sito1': '2-1',
    'sito0_5': '1-0.5',
    'sito0_25': '0.5-0.25',
    'sito0_1': '0.25-0.1',
    'sito0_05': '0.1-0.05',
    'sito0_01': '0.05-0.01',
    'sito0_002': '0.01-0.002',
    'sito_last': '<0.002',
    'density': 'Плотн. грунта',
    'particle_density': 'Плотн. част. гр.',
    'dry_density': 'Плотн. сух. гр.',
    'saturation_ratio': 'Ст. водонас.',
    'void_ratio': 'К-т пористости',
    'filtration': 'К-т фильтрации',
    'organic': 'Сод.орг.в-в',
    'uniformity_coefficient': 'К-т неоднородности гран.с-ва'
}
